init() := block(
	[
		plot_vars
	],

	Oscillator() := new(Model(
		"Harmonic oscillator",
		new(RKAdapter(
			[ y, -x ],
			[ x, y  ],
			[ 1, 0  ],
			[ t, 0, 10, 0.01 ]
		)),
		[
			[p] -> [ p[1], p[2] ],
			[p] -> [ p[1], p[3] ]
		]
	)),

	defstruct(OscillatorPlotVars(
		t,
		x,
		y
	)),

	plot_vars() := block([pv],
		pv : new(OscillatorPlotVars),
		pv@t : [p] -> p[1],
		pv@x : [p] -> p[2],
		pv@y : [p] -> p[3]
	)


) $
