defstruct(
	Model(
		name,
		rk_adapter,
		plot_groups
	)
) $

defstruct(
	RKAdapter(
		rhss,
		vars,
		initials,
		domain
	)
) $

defstruct(
	Domain(
		start,
		finish,
		stp
	)
) $

simulate(Mdl) := block([rka],
	rka : Mdl@rk_adapter,
	simulate_with(Mdl, rka@initials, rka@domain)
) $

simulate_with(Mdl, initials, domain) := block([rka],
	rka : Mdl@rk_adapter,
	rk(rka@rhss, rka@vars, initials, [ t, domain@start, domain@finish, domain@stp ])
) $

